version: "3"
services:
  xotomicro-front-product-service:
    build:
      context: ./
      dockerfile: docker/dockerfile.development
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: xotomicro-front-product-service
    ports:
      - 7073:7073
    volumes:
      - ./:/app
